- name: Execute playbooks
  hosts: all
  vars:
    service_list:
      "service1":
        - playbook1.yml
        - playbook2.yml
      "service2":
        - playbook2.yml
  tasks:
    - name: Creates working directory
      file:
        path: ~/{{service_name}}
        state: directory
    - name: Copy playbooks
      copy:
        src: "~/{{playbook_src}}/{{item}}"
        dest: "~/{{service_name}}"
      with_items: "{{service_list[(service_name)]}}"

