- name: Execute playbooks
  hosts: all
  vars:
    service_list:
      "service1":
        "file":
          - credentials.tf
          - otc1.tf
        "parameter":
          name: "{{name|default()}}"           
          flavor_id: "{{flavor_id|default()}}"    
      "service2":
        "file":
          - credentials.tf
          - otc2.tf
        "parameter":
          name: "{{name|default()}}"
          image_id: "{{image_id|default()}}"
  tasks:
    - name: Initialization
      set_fact:
        path: "/home/ubuntu/"
        dir_name: "{{service_name}}"
    - name: Create working directory
      file:
        path: "{{path+service_name}}"
        state: directory
    - name: Copy required providers
      copy:
        src: "{{path + provider_src}}/{{item}}"
        dest: "{path + service_name}}/"
        remote_src: yes
      with_items: "{{service_list[service_name].file}}"
    - terraform:
        project_path: '{{path + service_name}}'
        state: present
        force_init: true
        variables: "{{service_list[service_name].parameter}}"
