- name: Execute playbooks
  hosts: all
  tasks:
    - name: Creates working directory
      file:
        path: ~/{{service_name}}
        state: directory
    - name: Execute playbooks
      git:
        repo: https://github.com/awuuuuu/playbooks
        dest: "~/{{service_name}}"
    - name: Execute playbooks
      import_playbook: "~/{{service_name}}/{{playbook_name}}.yml"
