- name: Execute playbooks
  hosts: all
  tasks:
    - name: Execute playbooks
      command:
        argv:
          - cd ~/
          - mkdir {{service_name}}
          - cd {{service_name}}   
          - {{download_playbooks}}   
          - cd {{playbook_folder_name}}
          - ansible {{playbook_name}}
