- name: Execute playbooks
  hosts: all
  tasks:
    - name: Creates workding directory
      file:
        path: ~/{{service_name}}
        state: directory
    - name: Execute playbooks
      git:
        repo: https://github.com/awuuuuu/playbooks
        dest: "~/{{service_name}}"
- import_playbook: "/home/ubuntu/{{service_name}}/{{playbook_name}}.yml"

